# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: detect-secrets-ci

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toxenv:
          - py{36,37,38,39},mypy

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls tox==3.2 tox-pip-extensions==1.3.0 ephemeral-port-reserve
        tox -i https://pypi.python.org/simple -e ${{ matrix.toxenv }}
    - name: Test with pytest
      run: |
        pytest
